# 二つのサーバーを同時に起動するデモ
# 設定ファイルも個別に管理できます
# 事前に./config/craftopia-server-01 ./config/craftopia-server-02 のディレクトリを作成しておくことを推奨します
version: '3'
services:
  craftopia-server-01:
    image: ghcr.io/chujohiroto/docker-craftopia:latest
    restart: always
    ports:
      - "6587:6587/udp"
    volumes:
      - "./data/craftopia-server-01/ServerSetting.ini:/home/craftopia/.steam/steamapps/common/CraftopiaDedicatedServer/ServerSetting.ini"
      - "./data/craftopia-server-01/DedicatedServerSave:/home/craftopia/.steam/steamapps/common/CraftopiaDedicatedServer/DedicatedServerSave"
      - "./data/craftopia-server-01/log:/var/log/craftopia"
  craftopia-server-02:
    image: ghcr.io/chujohiroto/docker-craftopia:latest
    restart: always
    ports:
      - "6588:6587/udp"
    volumes:
      - "./data/craftopia-server-02/ServerSetting.ini:/home/craftopia/.steam/steamapps/common/CraftopiaDedicatedServer/ServerSetting.ini"
      - "./data/craftopia-server-02/DedicatedServerSave:/home/craftopia/.steam/steamapps/common/CraftopiaDedicatedServer/DedicatedServerSave"
      - "./data/craftopia-server-02/log:/var/log/craftopia"